### ISSUE TITLE
Resume/Shutdown the KCL

### ISSUE THREAD

**Issue by knexp** [evansolomon/nodejs-kinesis-client-library#11]
Do the KCL has the facility of shutdown/resuming the worker, in case of Database failure/Network Failure?

Thanks

**Comment by evansolomon** [comment]
Yup. Any time a worker exits (unless the shard is finished) it will be restarted. If the app is running across multiple hosts/processes, it may be restarted on a different one.

**Comment by knexp** [comment]
Sorry, I missed to elaborate the question,.

Can we explicitly shutdown  the KCL Worker? through the Consumer code?

Example  use case: consumer.js using another database(ex: MySQL) for the processing the job. When the MYSQL DB had outage, I need to PAUSE/shutdown The KCL until the DB is up.

do we have explicit control to shutdown/pause/resume the KCL through the code ??

**Comment by evansolomon** [comment]
Oh, I see. You'd have to stop the main process that's started by the CLI. The consumer app (the one that calls `kcl.extend()`) cannot shut down the whole app no matter what it does (within reason).

On the other hand, you could just let it keep running while the DB is down. It will keep failing and restarting itself at the last successful save point until things are back to normal.

**Comment by evansolomon** [comment]
Another option is that your consumer could do whatever status checks make sense and wait to call its callback until things are okay. That doesn't seem like the best idea to me, but obviously I don't know much about your situation so I can't say for sure whether it makes sense.  As a very quick example, something like this.

```js
kcl.extend({
  processRecords: function (records, callback) {
    waitForDbToBeOkay(function () {
      doStuff(records, callback)
    })
  }
})
```

**Comment by knexp** [comment]
thanks @evansolomon .
