### ISSUE TITLE
Network Distribution

### ISSUE THREAD

**Issue by basdag** [evansolomon/nodejs-kinesis-client-library#13]
Hello,

I am trying to deploy clusters in different machines consuming the same Kinesis Stream. The Wiki explains the concept of Networks and that it would try to rebalance shards across clusters. Therefore, my question would be how I can set and lunch a Network.

Thanks

**Comment by evansolomon** [comment]
Just run the same launch command on each host.

**Comment by basdag** [comment]
Ok that is what I thought, because all of them are pointing to the same Kinesis stream and using  the same DynamoDB table I believe. I was a little bit confuse about who was in charges of "automatically rebalance shards across clusters". Moreover, the reason for this clarification is because I went from one cluster in a machine to several clusters in different machines, and for I can see each cluster is getting stuck consuming the same piece of information from the Shard over and over again already in 48 hours. I made sure that once they were consuming the information the checkpoint, but still they go again an consumer the sam information from Kinesis.

**Comment by evansolomon** [comment]
Is there any other information you can give me? Each cluster should check for shards and compare them to the leases in the database. How many shards do you have? How many clusters?

**Comment by basdag** [comment]
Yes sure.

The Kinesis Shards went from 2 shards to 4 shards.
The Cluster went from 1 to 4 in different machines each one them.

I was checking the dynamo table and I saw in one point that the were 6 consumers for each one of the Cluster instances, which make in total 24 consumers for only for 4 shards.

Thanks.
