### ISSUE TITLE
Expose MillisBehindLatest as metric for processRecords

### ISSUE THREAD

**Issue by szinck** [evansolomon/nodejs-kinesis-client-library#14]
The Kinesis GetRecords call also returns MillisBehindLatest which would be interesting for client applications to use and graph.

https://github.com/evansolomon/nodejs-kinesis-client-library/blob/master/src/AbstractConsumer.ts#L245

However, when the callback to processRecords is called it extracts the Records field out.  It would be nice to pass the entire 'data' to consumers (which would break existing consumers) or devise another method to allow consumers access to this field.

**Comment by szinck** [comment]
https://github.com/evansolomon/nodejs-kinesis-client-library/pull/15 resolves this

**Comment by evansolomon** [comment]
Fixed via #16
