### ISSUE TITLE
Shutdown method

### ISSUE THREAD

**Issue by ThibaudDauce** [evansolomon/nodejs-kinesis-client-library#19]
Hi,

I was wondering how checkpoint after a shutdown method call. 
When a shard is finished, I need to save my current aggregation into my database one last time (to not lose data), so I push to my database the aggregation during the shutdown method. But if the KCL just kill the consumer for an other reason, I will push the aggregation to the database during the shutdown call and then restart the process from the last checkpoint. So I will have duplicate events into my database.

The two solutions I see are: call a checkpoint after the shutdown method or push to my database and checkpoint for each processRecords like it's done in the readme for S3 (not really good for performances).

Do you have an other idea to solve this problem? Can I call a checkpoint after the shutdown method?

Thanks a lot!

**Comment by evansolomon** [comment]
Sorry I missed this issue last week.

It sounds like what you want to do isn't currently supported but maybe should be. Could you post some example code for what your consumer module looks like? I want to make sure I understand the use case correctly. Feel free to simplify it as long as the main idea is there.
