### ISSUE TITLE
Allow maxCallFrequency to be configured

### ISSUE THREAD

**Issue by tvalletta** [evansolomon/nodejs-kinesis-client-library#20]
I need a little less latency in my kinesis consumer. I would like to set the maxCallFrequency down to the minimum value of 200 ms. Is there a chance that you could add this as an optional parameter on the cli?

http://docs.aws.amazon.com/kinesis/latest/dev/kinesis-low-latency.html

**Comment by evansolomon** [comment]
Check out the linked commit above and let me know if that seems right.

Do you have any thoughts about how throughput exceeded errors should be handled? Right now it waits 5 seconds and then tries again. Maybe that should be its own cli option? Or a multiple of the time between reads setting?

**Comment by evansolomon** [comment]
Thinking about this a bit more it seems like a much better solution would be to start with some small value and exponentially back off. I'll add that.

**Comment by evansolomon** [comment]
Published on npm as version 0.3.3. Hope this helps.

**Comment by tvalletta** [comment]
Went dark. Your changes look perfect. I will let you know if I run into issues. Thanks.
