### ISSUE TITLE
--num-records issue

### ISSUE THREAD

**Issue by knexp** [evansolomon/nodejs-kinesis-client-library#23]
Hi , 

When I pass --num-records 100, it is fetching greater than it.

 processRecords: function(records, done) {

}

record length is above the limit.

**Comment by evansolomon** [comment]
Can you paste the full command you're running?

**Comment by knexp** [comment]
launch-kinesis-cluster --consumer server.js --table table1--stream streamtest --aws.region us-east-1 --start-at latest --num-records 100

**Comment by evansolomon** [comment]
There should be a space between `table1` and `--stream`. Can you double check and make you paste exactly what's being run?

**Comment by knexp** [comment]
May be I'm using older version ?

**Comment by evansolomon** [comment]
> May be I'm using older version ?

Maybe :) What version are you using? That feature was added in version 0.2.7.

I just tried this myself and got the expected number of results per batch. You can check the package.json file in your modules directory (probably node_modules/kinesis-client-library/package.json).

**Comment by knexp** [comment]
Thanks worked .
