### ISSUE TITLE
Does two clusters in network,  process only one shard in kinesis?

### ISSUE THREAD

**Issue by knexp** [evansolomon/nodejs-kinesis-client-library#24]
I have two server, each running cluster pointing to same stream(only 1 shard),
when I see in dynamo table, only one cluster is processing, another have active consumer as 0.

is it expected or for two cluster application running we need 2 shards??

Thanks In Advance

**Comment by evansolomon** [comment]
Shards and consumers are 1 to 1. You can split the shard if you want to process it in parallel.

**Comment by knexp** [comment]
Thanks, got cleared.
