### ISSUE TITLE
Attempts to launch from another process

### ISSUE THREAD

**Issue by tvalletta** [evansolomon/nodejs-kinesis-client-library#26]
I am trying to launch my consumer from another process. When launching from the other process I set the "cwd" (current working directory) on this process, but it is ignored when attempting to resolve the path to the consumer. With a simple one line change, I believe that it can be fixed. See my patch below.

--- node_modules/kinesis-client-library/build/lib/cli.js	(revision )
+++ node_modules/kinesis-client-library/build/lib/cli.js	(revision )
@@ -38,7 +38,7 @@
     console.log('--time-between-reads (Time to wait between fetching records in milliseconds, defaults to 1000)');
     process.exit();
 }
-var consumer = path.resolve(process.env.PWD, args.consumer || '');
+var consumer = path.resolve(process.cwd(), args.consumer || '');
 var opts = {
     tableName: args.table,
     streamName: args.stream,

**Comment by evansolomon** [comment]
Thanks. This is now fixed and published as version `0.3.5`.

**Comment by tvalletta** [comment]
Perfect. Thanks.
