### ISSUE TITLE
Launching from nodejs itself

### ISSUE THREAD

**Issue by eridal** [evansolomon/nodejs-kinesis-client-library#30]
Hi @evansolomon et all

We are currently evaluating using the library to replace the java version from amazon.

We would like to have the client running inside an express app, running in a ebs for autoscaling purposes .. probably launched using pm2 in cluster mode.

Right now the library dont provide such functionality out of the box. What would you say be the best approach to achieve this? `spawn` a child process?

**Comment by evansolomon** [comment]
Yea `spawn` is probably the best approach.

An alternative is to look at what [the bin script](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/master/bin/launch) and/or [the CLI](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/master/src/lib/cli.ts) are doing. Depending on your use case you could choose to replicate some of that functionality if you need to.

**Comment by eridal** [comment]
@evansolomon Thanks for your reply

We endup taking some ideas from the helpers > https://github.com/evansolomon/nodejs-kinesis-client-library/blob/master/test/helpers/consumer.js#L9 but still thinking that using the `ConsumerCluster` api may be a better option.

**Comment by evansolomon** [comment]
Sounds good. 

Most of the relevant abstraction on top of ConsumerCluster is about handling errors and restarts, which you could do yourself just something to be careful with. There's also a bunch of code for local dev stuff hay you probably care less about (eg running a local dynamo server).

**Comment by evansolomon** [comment]
Closing since this seems resolved

**Comment by eridal** [comment]
Thanks @evansolomon
