### ISSUE TITLE
how to launch the cluster with sequence number, with iterater type AT_SEQUENCE_NUMBER?

### ISSUE THREAD

**Issue by knexp** [evansolomon/nodejs-kinesis-client-library#8]
The reason why I ask is , due to some failure the kinesis cluster is restarted ,  at this time how to process those un-processed data?

**Comment by evansolomon** [comment]
There isn't any way to do it with this library, which is mostly a design choice.

Sequence numbers are persisted in DynamoDB as they are processed.  If the cluster fails, the new cluster (or another existing cluster) will pick up after the last persisted sequence number.  The idea is that in doing this you get at-least-once processing and generally shouldn't need to care about particular sequence numbers, clusters, etc.

Let me know if you have a use case this doesn't work well for.

**Comment by knexp** [comment]
I use only one Cluster for Processing, I restarted the cluster, it does not process the data from the last persisted sequence number.

While restarting the cluster what Iterator type should I give ?

**Comment by knexp** [comment]
@evansolomon  I have found the root cause, every time I restart the cluster, the local dynamo table is created newly, I'll try with the AWS Dynamo Table and keep you posted.

**Comment by knexp** [comment]
This has been fixed. By using --dynamo-directory while launching the issue has been fixed.
Thanks @evansolomon

**Comment by evansolomon** [comment]
Cool.  Fyi the local dynamo option is really only intended for testing.  For anything you want to be persistent I strongly recommend using the real dynamodb.

**Comment by knexp** [comment]
Thanks @evansolomon for the information. :)
