### ISSUE TITLE
Conditional check failed

### ISSUE THREAD

**Issue by rclark** [evansolomon/nodejs-kinesis-client-library#9]
I had an issue where the KCL became stuck in a loop of repeating reads without checkpointing new sequence numbers. I'm having some trouble debugging this, but my hunch is that somehow the process lost track of the lease number and was unable to get a new lease.

To give you a sense of the loop, here are the series of abbreviated messages that were running

"Setting up lease"
"Got starting checkpoint"
"Updating shard iterator"
"Updated shard iterator"
"No initialize method defined, skipping"
"Starting getRecords loop"
"Starting reserveLease loop"
"The conditional request failed"
--ConditionalCheckFailedException--
"Starting shutdown"
"No shutdown method defined, skipping"
(repeat)

The exception:
```json
{
    "name": "KinesisConsumer",
    "streamName": "Stream-1VYNRPNW0VU0L",
    "shardId": "shardId-000000000000",
    "hostname": "ip-xx-xxx-xxx-xxx",
    "pid": 15248,
    "level": 50,
    "err": {
        "message": "The conditional request failed",
        "name": "ConditionalCheckFailedException",
        "stack": "...(see below)...",
        "code": "ConditionalCheckFailedException"
    },
    "msg": "The conditional request failed",
    "time": "2015-03-18T18:29:16.594Z",
    "v": 0
}
```

The stack trace isn't too helpful because it doesn't make it back into kcl code:
```
ConditionalCheckFailedException: The conditional request failed
    at Request.extractError (/usr/local/src/app/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/usr/local/src/app/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/usr/local/src/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/src/app/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/usr/local/src/app/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/usr/local/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/src/app/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/usr/local/src/app/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/usr/local/src/app/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

I don't quite understand how the process maintains the lease number that it should be using. We shut the process down for several days, and when we started it again it seemed to continue just fine.

**Comment by evansolomon** [comment]
> I had an issue where the KCL became stuck in a loop of repeating reads without checkpointing new sequence numbers

Would it be possible to share your consumer code (particularly the `processRecords` part)?

On its own, there's really nothing wrong with a conditional check failing (it usually catches what would otherwise be a race condition).  Obviously it shouldn't loop and fail forever though.  One thing that could cause that kind of issue is if your `processRecords` method blocks the event loop for a very long time (e.g. 10+ seconds).

> I don't quite understand how the process maintains the lease number that it should be using. We shut the process down for several days, and when we started it again it seemed to continue just fine.

There are a couple different processes involved, but in general the logic goes like this:

1. A manager process finds an available shard and reads its lease number (this is just a monotonic increasing integer)
2. The manager passes information about the shard (including its lease number) to a child process that will consume the shard
3. When the child boots up it tries to increment the lease counter by 1 but only does so if the value matches whatever the manager process passed in, otherwise it fails
4. Every 5 seconds, the child increments the lease counter by 1 and adds 15 seconds to an expiration time

The result of all this is that multiple workers can compete for the same shard and trust that only one of them will "win" based on the expected lease number.

**Comment by rclark** [comment]
[Here's the code](https://github.com/mapbox/dynamodb-replicator/blob/5166f69f1c8e3c8988a9b7d9d7c19ae44bbbf594/index.js#L35-L62) -- its definitely not blocking the event loop -- its simply read from one dynamo table, write to another.

We only had one shard in the stream at the time. There was also only one consumer machine running. I'm not sure how to search our logs to determine if there was more than one consumer process on that machine involved at the time. Any tips? Log messages to look for?

**Comment by evansolomon** [comment]
> I'm not sure how to search our logs to determine if there was more than one consumer process on that machine involved at the time. Any tips? Log messages to look for?

The simplest way to tell would be to look at the `pid` field in the logs.  At any given time, you could expect `name` + `streamName` + `shardId` to be a unique identifier for a consumer process.  If multiple processes have the same params at the same time, then you'd have multiple processes trying to consume the same shard (which isn't supposed to happen).  The tricky bit is that obviously pid's will change across restarts, and if your consumers are launching/crashing over and over you're going to have a bunch of restarts.

The other thing you can check while it's happening is the DynamoDB table that the consumers are using.  If you only have one machine and one shard you would expect to see 2 rows that look kind of like this.

![image](https://cloud.githubusercontent.com/assets/407310/6909174/4e781924-d6f8-11e4-8c59-fc49bf6464cf.png)

**Comment by rclark** [comment]
Here are some more logs, truncated, but what I'm seeing here is multiple pids, all with the same name + streamName + shardId "which isn't supposed to happen"??

```
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":30,"msg":"Starting shutdown",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":50,"err":{"message":"The conditional request failed",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":19081,"level":30,"msg":"Starting reserveLease loop",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":19081,"level":30,"msg":"Starting getRecords loop",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":19081,"level":30,"msg":"No initialize method defined, skipping",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":19081,"level":30,"ShardIterator":"AAAAAAAAAAGnwFx9ZSoCYzr
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":19081,"level":30,"iteratorType":"AFTER_SEQUENCE_NUMBER",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":19081,"level":30,"checkpoint":"49548121196260673560016602428939911194087687821839040514","msg":"Got starting checkpoint",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":19081,"level":30,"leaseCounter":520957,"tableName":"table-kinesis-stream-cluster","msg":"Setting up lease",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":15248,"level":30,"msg":"No shutdown method defined, skipping",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":15248,"level":30,"msg":"Starting shutdown",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":15248,"level":50,"err":{"message":"The conditional request failed",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":30,"msg":"Starting reserveLease loop",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":30,"msg":"Starting getRecords loop",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":30,"msg":"No initialize method defined, skipping",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":30,"ShardIterator":"AAAAAAAAAAHyjdgKr4yr21/wY
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":30,"iteratorType":"AFTER_SEQUENCE_NUMBER",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":30,"checkpoint":"49548121196260673560016602428939911194087687821839040514","msg":"Got starting checkpoint",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":18892,"level":30,"leaseCounter":520955,"tableName":"table-kinesis-stream-cluster","msg":"Setting up lease",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":15248,"level":30,"ShardIterator":"AAAAAAAAAAE6VyPLImlcZDOCifT
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":15248,"level":30,"iteratorType":"AFTER_SEQUENCE_NUMBER",
{"name":"KinesisConsumer","streamName":"Stream-1VYNRPNW0VU0L","shardId":"shardId-000000000000","hostname":"ip-xx-xxx-xx-xxx","pid":15248,"level":30,"msg":"Shard iterator expired, updating before next getRecords call",
```

**Comment by evansolomon** [comment]
Yea it does seem like there are multiple processes going on the same shard at the same time.

When this happens, does it go on indefinitely?  It's not supposed to happen, but the cluster should also be able to recover itself (even if some processes do crash in the meantime).  I'd expect the flow to look something like

1. Something weird happens and multiple consumers are assigned to the same shard
2. One or many consumers crash with the "conditional request failed" message

At that point the most likely outcome is that one consumer survives because it got its write in before all the others, so its conditional requests are always successful.

The less likely but probably theoretically possible scenario is that somehow all of the consumers crash.  At this point the lease is still "reserved" because its expiration time has not come yet, so the cluster just chills out and keep checking for available shards.  Once the expiration time hits, it finds an available shard and assigns it to a consumer, and everything goes along okay from there.

Can you check for logs with `KinesisCluster` as the `name` property?  Particularly interesting ones would be `Found available shard` and `Spawning consumer`.

**Comment by rclark** [comment]
> Can you check for logs with KinesisCluster as the name property? Particularly interesting ones would be Found available shard and Spawning consumer.

Sure enough, these messages are cycling throughout the incident (again, oldest at the bottom, newest at the top)

```
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","msg":"Consumer exited"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","leaseCounter":520959,"msg":"Spawning consumer"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","leaseCounter":520959,"msg":"Found available shard"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"msg":"Garbage collecting clusters","time":"2015-03-18T18:29:50.300Z","v":0}"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","msg":"Consumer exited"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","leaseCounter":520957,"msg":"Spawning consumer"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","leaseCounter":520957,"msg":"Found available shard"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","msg":"Consumer exited"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","leaseCounter":520955,"msg":"Spawning consumer"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"shardId":"shardId-000000000000","leaseCounter":520955,"msg":"Found available shard"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"msg":"Garbage collecting clusters","time":"2015-03-18T18:28:50.038Z","v":0}"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"msg":"Garbage collecting clusters","time":"2015-03-18T18:27:49.824Z","v":0}"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"msg":"Garbage collecting clusters","time":"2015-03-18T18:26:49.535Z","v":0}"
{"name":"KinesisCluster","hostname":"ip-xx-xxx-xx-xxx","pid":8079,"level":30,"msg":"Garbage collecting clusters","time":"2015-03-18T18:25:49.307Z","v":0}"
```

This pinpoints when whatever happened occurred -- as the logs switch from minutely "Garbage collecting clusters" to cycling spawning/exiting messages.

> When this happens, does it go on indefinitely?

We allowed it to go on for ~8 hours before we shut it down. I didn't actually do the shutting down, but apparently the EC2 was killed, a new one started up in its place *and the situation continued*. Then we shut it down for several days, and upon resuming everything worked as expected.

**Comment by evansolomon** [comment]
This batch of logs looks like this cluster is only starting one consumer at a time, whereas the last batch looked like multiple consumers were active at once.  That does seem strange.

One thing the library could do to help you out here is include the cluster pid in the consumer logs.  That way it would be easier to tell which processes are owned by which other process.

**Comment by rclark** [comment]
More log snooping, this time edited and in chronological order. 15248 appears to be the first consumer to encounter the ConditionalCheckFailed exception:

```
03/18/2015 11:28:59.000: "KinesisConsumer" "pid":15248 "Shard iterator expired, updating before next getRecords call"
03/18/2015 11:28:59.000: "KinesisConsumer" "pid":15248 "Updating shard iterator"
03/18/2015 11:28:59.000: "KinesisConsumer" "pid":15248 "Updated shard iterator"
03/18/2015 11:29:15.000: "KinesisCluster" "leaseCounter":520955 "pid":8079 "Found available shard"
03/18/2015 11:29:15.000: "KinesisCluster" "leaseCounter":520955 "pid":8079 "Spawning consumer"
03/18/2015 11:29:15.000: "KinesisConsumer" "leaseCounter":520955 "pid":18892 "Setting up lease"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":18892 "Got starting checkpoint"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":18892 "Updating shard iterator"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":18892 "Updated shard iterator"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":18892 "No initialize method defined, skipping"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":18892 "Starting getRecords loop"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":18892 "Starting reserveLease loop"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":15248 "ConditionalCheckFailedException"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":15248 "Starting shutdown"
03/18/2015 11:29:16.000: "KinesisConsumer" "pid":15248 "No shutdown method defined, skipping"
03/18/2015 11:29:16.000: "KinesisCluster" "pid":8079 "Consumer exited" 
03/18/2015 11:29:40.000: "KinesisCluster" "leaseCounter":520957 "pid":8079 "Found available shard"
... starts up a consumer with pid 19081 which updates the shard iterator, starts loops ...
03/18/2015 11:29:46.000 "KinesisConsumer" "pid":18892 "ConditionalCheckFailedException"
```

So the consumer processes seem to start leapfrogging each other.

> include the cluster pid in the consumer logs

So far as I've seen in these logs there's only one cluster pid, 8079.

**Comment by evansolomon** [comment]
So there is a consumer running (15248) and the cluster finds an available shard when it shouldn't.

I'm pretty sure your case is hitting [this code path](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/1b53e2b5b58b4144b2a7cea332e4e1aaac682585/src/ConsumerCluster.ts#L246-L257), which means that the shard looks like it has an expired lease.

When a lease is reserved/updated, its `expiresAt` property is set to 15 seconds in the future.  The consumer updates the lease every 5 seconds.

It's hard to guess exactly why this is (or was) happening.  Here are a few ideas off the top of my head.

* The event loop blocking thing I mentioned before (but I agree it seems unlikely your processor is doing this)
* Some kind of weird clock skew where it thinks leases are expired < 5 seconds after they're updated
* Really high latency in DynamoDB writes that cause the lease update interval to fall outside the expiration time

**Comment by rclark** [comment]
Really appreciate your taking a look here. I'm getting the hang of the logging and the code flow, and I see what you mean - it would appear that for whatever reason to first consumer's request to update the lease failed, or took a terribly long time. I looked at Cloudwatch for any indication of throughput issues or write latency on the table but didn't find anything.

For my reference moving forward, how can I enable debug logging? I noticed that there are a few more messages that might be useful to see the timing of related to lease updating.

**Comment by evansolomon** [comment]
> how can I enable debug logging?

Unfortunately there's no good way to do this right now.  I wish Bunyan let you use environment variables for this, but it has to be done when you instantiate a logger.

I can add support for it in a command line flag though.  Shouldn't be too hard.

**Comment by evansolomon** [comment]
I added a new CLI arg `--log-level` which you can set to `debug` to get all missing logs.  It's tagged/published to NPM as version 0.2.5.

**Comment by rclark** [comment]
Thanks! Hopefully this situation doesn't come up again, but if it does I'll let you know, and maybe have some more logs to look at.

Nothing really actionable in this ticket, so please feel free to close it if you want to.

**Comment by evansolomon** [comment]
Cool.  Sorry I didn't have better answers.  I'll close this, but don't hesitate to open a new one or ping me if something else comes up.
